- name: Create SSH security group
  openstack.cloud.security_group:
    cloud: "{{ cloud }}"
    name: sg-ssh
    description: ssh access

- name: Add rules to security group
  openstack.cloud.security_group_rule:
    cloud: "{{ cloud }}"
    security_group: sg-ssh
    port_range_max: 22
    port_range_min: 22
    protocol: tcp
    remote_ip_prefix: 0.0.0.0/0
