- name: Get running instances
  openstack.cloud.server_info:
    cloud: "{{ cloud }}"
    filters:
      vm_state: active
  register: servers

- name: Stop instances
  openstack.cloud.server_action:
    cloud: "{{ cloud }}"
    server: "{{ item.id }}"
    action: stop
    wait: no
  loop: "{{ servers.openstack_servers }}"
  loop_control:
    label: "{{ item.name }}"
  async: 300
  poll: 0 
